dbt_ecom_sales:
  outputs:
    dev:
      dataset: raw_datasets
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: dbt-e-com-sales-ec3259e5e9a2.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-e-com-sales
      threads: 1
      type: bigquery
  target: dev
